In [1]:
# Numbers and strings
age = 21
gpa = 3.85
name = "Aiyana"

# List: ordered, mutable
grades = [88, 91, 76, 95]
grades.append(84)

# Tuple: ordered, immutable
point = (37.5, 127.0)

# Dictionary: key-value pairs
student = {
    "name": name,
    "gpa": gpa,
    "grades": grades
}

In [2]:
value = 120
mean = 50
threshold = 2 * 50  # example threshold

if value > mean + threshold:
    flag = "High outlier"
elif value < mean - threshold:
    flag = "Low outlier"
else:
    flag = "Normal"

In [3]:
# Example: calculate the average value
# for each row in a dataset
import pandas as pd

data = [
    {"name": "Alice", "score": 85},
    {"name": "Bob", "score": 92},
    {"name": "Charlie", "score": 78}
]

df = pd.DataFrame(data)

# Loop through each row
for index, row in df.iterrows():
    name = row["name"]
    score = row["score"]
    print(f"{name}: {score}")

Alice: 85
Bob: 92
Charlie: 78


In [4]:
# Start from 1 and keep going
# while the counter is less than or equal to 5
count = 1

while count <= 5:
    print(f"Count: {count}")  # do the action
    count += 1                # update the counter

print("Loop finished!")

Count: 1
Count: 2
Count: 3
Count: 4
Count: 5
Loop finished!


In [5]:
scores = [55, 88, 72, 40, 95]
passed = []

for s in scores:
    if s >= 60:
        passed.append(s)
    else:
        print(f"Review needed: {s}")

pass_rate = len(passed) / len(scores)

if pass_rate >= 0.8:
    print("Strong cohort result")
elif pass_rate >= 0.5:
    print("Mixed result")
else:
    print("Needs review")

Review needed: 55
Review needed: 40
Mixed result


In [6]:
def greet(name):
    print(f"Hello, {name}!")

    return f"Hello, {name}!"

In [7]:
print(greet("Alice"))
print(greet("Bob"))
print(greet("Charlie"))

Hello, Alice!
Hello, Alice!
Hello, Bob!
Hello, Bob!
Hello, Charlie!
Hello, Charlie!


In [8]:
def normalize(values):
    """Scale values to a 0-1 range."""
    low = min(values)
    high = max(values)
    return [(v - low) / (high - low)
            for v in values]

def average(values):
    return sum(values) / len(values)

grades = [88, 91, 76, 95, 84]

scaled = normalize(grades)
mean_grade = average(grades)

print(mean_grade)
print(scaled)

86.8
[0.631578947368421, 0.7894736842105263, 0.0, 1.0, 0.42105263157894735]


In [9]:
# Writing lines to a file
students = ["Aiyana", "Minho", "Zainab"]

with open("roster.txt", "w") as f:
    for name in students:
        f.write(name + "\n")

# Reading the file back
with open("roster.txt", "r") as f:
    lines = f.readlines()

names = [line.strip() for line in lines]
print(names)

# ['Aiyana', 'Minho', 'Zainab']

['Aiyana', 'Minho', 'Zainab']


In [10]:
import numpy as np
# 2 × 3 array of integers
arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int32)
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
import numpy as np

# From a Python list
a = np.array([1, 2, 3, 4, 5])

# Common constructors
zeros = np.zeros((3, 4))
ones = np.ones((2, 2))
seq = np.arange(0, 10, 2)
grid = np.linspace(0, 1, 5)

# A 2D array (matrix)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print(matrix.shape)  # (2, 3)

(2, 3)


In [12]:
prices = np.array([19.99, 45.00, 8.50])
quantities = np.array([2, 1, 5])

# Element-wise operations - no loop!
totals = prices * quantities
print(totals)
# [ 39.98  45.    42.5 ]

discounted = prices * 0.9

# Aggregate functions
print(totals.sum())    # 127.48
print(prices.mean())   # 24.4966...
print(prices.max())    # 45.0

[39.98 45.   42.5 ]
127.47999999999999
24.496666666666666
45.0


In [13]:
total = 0
for i in range(len(prices)):
    total += prices[i] * quantities[i]

In [14]:
total = (prices * quantities).sum()

In [15]:
import numpy as np

A = np.array([[10, 20, 30],
              [40, 50, 60]])  # shape (2, 3)
b = np.array([1, 2, 3])       # shape (3,)
A + b

array([[11, 22, 33],
       [41, 52, 63]])

In [16]:
A + b   # (2, 3) + (3,) -> (2, 3)
A - b   # (2, 3) - (3,) -> (2, 3)
A * b   # (2, 3) * (3,) -> (2, 3)

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [17]:
temps_celsius = np.array([
    [20, 22, 19],
    [25, 27, 24]
])

# A single number broadcasts
# across the whole array
temps_fahrenheit = temps_celsius * 9/5 + 32

# A 1D array broadcasts across rows
row_adjustment = np.array([1, 0, -1])
adjusted = temps_celsius + row_adjustment

print(adjusted)
# [[21 22 18]
#  [26 27 23]]

[[21 22 18]
 [26 27 23]]


In [18]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
b = np.array([10, 20, 30, 40, 50], dtype=float)

result = []
for x, y in zip(a, b):
    result.append(x + y)

result = np.array(result)

In [19]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
b = np.array([10, 20, 30, 40, 50], dtype=float)

result = a + b  # vectorized operation

In [20]:
import numpy as np
import time

n = 5_000_000
a = list(range(n))
b = np.arange(n)

start = time.time()
result = [x * 2 for x in a]
print("Python loop:", time.time() - start)

start = time.time()
result = b * 2
print("NumPy vectorized:", time.time() - start)

# Python loop:      ~0.35 sec
# NumPy vectorized: ~0.01 sec

Python loop: 0.06139516830444336
NumPy vectorized: 0.03183913230895996
